create table application_option(
    ao_id bigint generated by default as identity,
	ao_key varchar(255) not null,
	ao_value varchar(255)
);

insert into application_option(ao_key, ao_value) values ('key1', 'value1')