
create role application_user;

create table application_option(
    ao_id bigint generated by default as identity,
    ao_group integer,
	ao_key varchar(255) not null,
	ao_value varchar(255)
);

insert into application_option(ao_group, ao_key, ao_value) values (1, 'key0', 'value0');
insert into application_option(ao_group, ao_key, ao_value) values (1, 'key1', 'value1');
insert into application_option(ao_group, ao_key, ao_value) values (2, 'key2', 'value2');
insert into application_option(ao_group, ao_key, ao_value) values (2, 'key3', 'value3');

alter table application_option enable row level security;

create policy application_option_policy on application_option to application_user using (
    current_setting('my.var', true) is null or current_setting('my.var', true)::integer = ao_group
);


-- note: this grant must be done _after_ creating all the tables.
-- note: need to grand access to other objects too (sequences, etc)
grant all on all tables in schema public to application_user;
